CREATE TABLE Realtors (
	Comm INTEGER NOT NULL,
	pid INTEGER NOT NULL,
	Realtors_pid INTEGER NOT NULL,
	CONSTRAINT PK_Realtors5 PRIMARY KEY (pid)
	);
CREATE INDEX TC_Realtors8 ON Realtors (Realtors_pid );
CREATE INDEX TC_Realtors9 ON Realtors (pid );
CREATE TABLE Person (
	pid INTEGER NOT NULL,
	name VARCHAR ( 255 ),
	CONSTRAINT PK_Person0 PRIMARY KEY (pid)
	);
CREATE TABLE Regions (
	rid INTEGER NOT NULL,
	name VARCHAR ( 255 ) NOT NULL,
	CONSTRAINT PK_Regions1 PRIMARY KEY (rid)
	);
CREATE TABLE R2R (
	StartDate DATE NOT NULL,
	rid INTEGER NOT NULL,
	pid INTEGER NOT NULL,
	CONSTRAINT PK_R2R3 PRIMARY KEY (pid, rid)
	);
CREATE INDEX TC_R2R2 ON R2R (rid );
CREATE INDEX TC_R2R10 ON R2R (pid );
CREATE TABLE Properties (
	pid INTEGER NOT NULL,
	name VARCHAR ( 255 ) NOT NULL,
	address VARCHAR ( 255 ) NOT NULL,
	Properties_ID INTEGER NOT NULL,
	rid INTEGER NOT NULL,
	CONSTRAINT PK_Properties4 PRIMARY KEY (Properties_ID)
	);
CREATE INDEX TC_Properties11 ON Properties (rid );
ALTER TABLE R2R ADD CONSTRAINT FK_R2R5 FOREIGN KEY (pid) REFERENCES Realtors (pid)  ON DELETE CASCADE;
ALTER TABLE R2R ADD CONSTRAINT FK_R2R1 FOREIGN KEY (rid) REFERENCES Regions (rid)  ON DELETE CASCADE;
ALTER TABLE Realtors ADD CONSTRAINT FK_Realtors4 FOREIGN KEY (Realtors_pid) REFERENCES Realtors (pid)  ON DELETE SET NULL;
ALTER TABLE Realtors ADD CONSTRAINT FK_Realtors6 FOREIGN KEY (pid) REFERENCES Person (pid)  ON DELETE CASCADE;
ALTER TABLE Properties ADD CONSTRAINT FK_Properties3 FOREIGN KEY (rid) REFERENCES Regions (rid)  ON DELETE SET NULL;

